# Generated by Django 2.1.7 on 2019-03-12 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('percent', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeOutgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=16)),
                ('outgo', models.DecimalField(decimal_places=2, max_digits=16)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.DownloadedFile')),
            ],
        ),
    ]
