# Generated by Django 2.1.7 on 2019-04-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_downloadedfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedfile',
            name='percent',
        ),
        migrations.AddField(
            model_name='downloadedfile',
            name='project_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
