# Generated by Django 2.1.7 on 2019-04-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190420_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedfile',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
