# Generated by Django 2.1.7 on 2019-04-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_downloadedfile_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedfile',
            name='irr',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
