# Generated by Django 2.1.7 on 2019-04-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_downloadedfile_irr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedfile',
            name='irr',
            field=models.CharField(max_length=255),
        ),
    ]
